# Generated by Django 6.0 on 2025-12-27 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('RAM', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=50)),
                ('release_date', models.IntegerField(max_length=50)),
                ('price', models.CharField(max_length=50)),
            ],
        ),
    ]
