# Generated by Django 6.0 on 2025-12-27 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phone',
            old_name='RAM',
            new_name='storage',
        ),
    ]
